name: 'easyhl7_dev'
version: '0.1.0'

config-version: 2

profile: 'easyhl7'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  easyhl7_dev:

    v2_1:
      +database: v2_1
      +tags:
        - v2_1
      
      oru:
        r01:
          +schema: oru_r01
          +tags:
            - oru_r01
      orm:
        o01:
          +schema: orm_o01
          +tags:
            - orm_o01

seeds:
  easyhl7_dev:
    samples:
      v2_1:
        +schema: raw

      v2_2:
        +schema: raw