name: 'easyhl7_dev'
version: '0.1.0'

config-version: 2

profile: 'easyhl7'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  easyhl7_dev:

    v2_1:
      oru:
        r01:
          +schema: oru_r01
      orm:
        o01:
          +schema: orm_o01

    v2_2:
      oru:
        r01:
          +schema: oru_r01
      orm:
        o01:
          +schema: orm_o01

    v2_3:
      oru:
        r01:
          +schema: oru_r01
      orm:
        o01:
          +schema: orm_o01

seeds:
  easyhl7_dev:
    samples:
      v2_1:
        +schema: raw_v2_1
      v2_2:
        +schema: raw_v2_2
      v2_3:
        +schema: raw_v2_3